{
 "title": "Kafka Exporter",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(kafka_consumergroup_lag{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, consumergroup)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message per sec",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~\"$instance\", consumergroup=\"$group\"}[1m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~\"$instance\", consumergroup=\"$group\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$topic\", consumergroup=~\"$group\"}) by (consumergroup, topic, partition)",
     "legendFormat": "{{ partition}} : {{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "OpenTSDB DOWN SERVERS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "count(haproxy_server_up{backend=~\"be_opentsdb\",instance=~\"atlas-haproxy01\"}) - sum(haproxy_server_up{backend=~\"be_opentsdb\",instance=~\"atlas-haproxy01\"} == 1)"
    }
   ]
  },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}[1m])) by (topic, partition)",
     "legendFormat": "{{ partition}} : {{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~\"$instance\",topic=~\"$topic\", consumergroup=\"$group\"}[5m])/5) by (consumergroup, topic, partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group Total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$topic\", consumergroup=~\"$group\"}) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"otwamp\", consumergroup=~\"opentsdb_twamp_writer\"}) by (consumergroup, topic, partition)",
     "legendFormat": "{{ partition}} : {{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group Stacked",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$topic\", consumergroup=~\"$group\"}) by (consumergroup, topic, partition)",
     "legendFormat": "{{ partition}} : {{consumergroup}} (topic: {{topic}})"
    }
   ]
  }
 ]
}