apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  namespace: kafka
  name: grafana
spec:
  config: {}
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [ grafana ] }