apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
  namespace: kafka
spec:
  staticScrapeSelector: {}
  resources:
    limits:
      cpu: 500m
      memory: 850Mi
    requests:
      cpu: 250m
      memory: 350Mi
  serviceScrapeSelector: {}
  extraArgs:
    memory.allowedPercent: '40'
  probeSelector: {}
  nodeScrapeSelector: {}
  replicaCount: 1
  podScrapeSelector: {}
  remoteWrite:
    - url: 'http://vminsert-simple:8480/insert/0/prometheus/api/v1/write'
